### ISSUE TITLE
Cannot import name 'float' from 'numpy'

### ISSUE THREAD

**Issue by nw0428** [Christopher-Thornton/hmni#21]
I am getting this stack trace when I try to input hmni

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.10/site-packages/hmni/__init__.py", line 1, in <module>
    from . import input_helpers, matcher, preprocess, siamese_network, syllable_tokenizer
  File "/opt/homebrew/lib/python3.10/site-packages/hmni/matcher.py", line 30, in <module>
    from abydos.distance import (IterativeSubString, BISIM, DiscountedLevenshtein, Prefix, LCSstr, MLIPNS, Strcmp95,
  File "/opt/homebrew/lib/python3.10/site-packages/abydos/distance/__init__.py", line 368, in <module>
    from ._aline import ALINE
  File "/opt/homebrew/lib/python3.10/site-packages/abydos/distance/_aline.py", line 25, in <module>
    from numpy import float as np_float
ImportError: cannot import name 'float' from 'numpy' (/opt/homebrew/lib/python3.10/site-packages/numpy/__init__.py)
```

**Comment by pwrose** [comment]
I'm getting the same error with Python 3.8.

**Comment by bwo** [comment]
yep. same with 3.11. presumably it's a matter of the numpy version. this is really an issue in `abydos`, though
